### ISSUE TITLE
Achievement text and trigger condition one order of magnitude apart from each other

### ISSUE THREAD

**Issue by nekizalb** [sudo-ellipsis/SequentialLimits#1]
My apologies if I'm misunderstanding the math here, but I noticed something odd while playing today and wanted to share

Achievements 8 through 16 all say 'Get your approximation of e to 10^-[X] off true", but the trigger condition is set to 1eX, causing the achievement to award at a lower value than the text indicates. 

For example, during play today, I was awarded Precision Player when my e-γ=1e-100, not the 10e-100 the achievement text described. 

Achievement 7 seems to correct this by having the text state 10^-1 and the trigger be 1e0.

Again, apologies if I'm misunderstanding the math, but figured I would share in case I am right. If nothing else, it was confusing as the player for the achievement and onscreen numbers to not match when the achievement triggered. 

Thanks!

**Comment by makingtronics** [comment]
Hey, thanks for the issue :)
8-16 are correct - 1/(1e100) is 1e-100, meaning the difference is 1e-100. However, it turns out 7 is incorrect - that should be 1e1, as it triggers when e-γ <= 1/(10^0) <= 1. Oops.
Admittedly, I might be getting this wrong - I'll look at it again in the morning.

**Comment by nekizalb** [comment]
Right, I agree with this line
 *1/(1e100) is 1e-100, meaning the difference is 1e-100
But the achievement says it triggers when the difference is 10e-100 (ten, not one). I think that's my confusion 

Either way, yeah, at least one of them is wrong for sure =)
